# Generated by Django 4.2.19 on 2025-03-14 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorsavedstartup',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Share of investment in percentage (0 - 100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
