# Generated by Django 4.2.19 on 2025-03-22 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0002_alter_investortrackedproject_unique_together_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('project_follow', 'Project follower changed'), ('investor_follow', 'Investor follows startup'), ('startup_follow', 'Startup follower changed'), ('project_profile_update', 'Project profile update'), ('startup_profile_update', 'Startup profile update'), ('investor_profile_update', 'Investor profile update'), ('system_message', 'System message')], db_index=True, max_length=40)),
                ('initiator', models.CharField(choices=[('investor', 'Investor'), ('startup', 'Startup'), ('project', 'Project'), ('system', 'System')], max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', max_length=40)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=notifications.models.get_expiration_date)),
                ('investor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='investors.investorprofile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='startups.startupprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient', 'is_read', 'priority', 'trigger'], name='notificatio_recipie_59511f_idx')],
            },
        ),
    ]
