# Generated by Django 4.2.19 on 2025-03-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_logo', models.ImageField(blank=True, null=True, upload_to='startup_logos/')),
                ('industries', models.ManyToManyField(blank=True, related_name='startups', to='startups.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='StartupIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_links', to='startups.industry')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_links', to='startups.startupprofile')),
            ],
            options={
                'unique_together': {('startup', 'industry')},
            },
        ),
    ]
