# Generated by Django 4.2.19 on 2025-03-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Seeking Funding', 'Seeking Funding'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='project_business_plans/')),
                ('media_files', models.FileField(blank=True, null=True, upload_to='project_media/')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='startups.startupprofile')),
            ],
        ),
    ]
